version: "2"
services:
    test:
        environment:
          - uuidsecretanalytics
          - mongodbatlas
          - ziip
        build:
            context: .
            dockerfile: tests/Dockerfile
        image: ziwebcounter:test
    release:
        build:
            context: .
            dockerfile: Dockerfile
        image: swr.eu-de.otc.t-systems.com/zi_container_repositories/ziwebcounter:mongodbatlas
