# This is a basic workflow to help you get started with Actions

name: Build and Upload Docker image

# Controls when the action will run. 
on:
  # If new API Release is created
  release:
    types: [created]  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build and run test Container
        env: 
          mongodbatlas: ${{ secrets.mongodbatlas }}
          uuidsecretanalytics: ${{ secrets.uuidsecretanalytics }}
        run: |
          docker-compose build test
          docker-compose run --rm test          
  
      - name: login to azure
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: build and upload release container
        run: |
          docker-compose build release
          docker-compose push release    
